# Generated by Django 4.2.5 on 2023-11-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0002_alter_dietmeal_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietmeal',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
