# Generated by Django 4.2.5 on 2023-11-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0003_alter_dietmeal_quantity_alter_meal_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiet',
            name='diet_type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='fish_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='lactose_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='meal_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='nut_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='preferences_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='soy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdiet',
            name='data_zakonczenia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
        ),
    ]
