# Generated by Django 4.2.5 on 2023-11-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0004_userdiet_diet_type_userdiet_fish_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='userdiet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inz_server.userdiet'),
        ),
    ]
