# Generated by Django 4.2.5 on 2023-11-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0006_rename_userdiet_zamowienie_user_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiet',
            name='food_preferences',
            field=models.JSONField(default=dict),
        ),
    ]
