# Generated by Django 4.2.5 on 2023-11-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0007_userdiet_food_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='fish_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='gluten_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='lactose_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='nut_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='soy_free',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inz_server.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inz_server.meal')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inz_server.measurementunit'),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inz_server.measurementunit'),
        ),
    ]
