# Generated by Django 4.2.5 on 2023-12-01 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0014_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 21, 19, 10, 319186)),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
