# Generated by Django 4.2.5 on 2023-12-01 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0015_emailverificationtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 22, 6, 41, 642517)),
        ),
    ]
