# Generated by Django 4.2.5 on 2023-12-02 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0016_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 17, 36, 7, 558647)),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('aipending', '[AI] Pending'), ('completed', 'Completed'), ('aicompleted', '[AI] Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
        ),
    ]
