# Generated by Django 4.2.5 on 2023-12-08 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0017_alter_emailverificationtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 13, 51, 42, 999769)),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('aipending', '[AI] Pending'), ('aicompleted', '[AI] Completed')], default='pending', max_length=100),
        ),
    ]
