# Generated by Django 4.2.5 on 2023-12-08 14:09

from django.db import migrations, models
import inz_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0018_alter_emailverificationtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=inz_server.models.default_expires_at),
        ),
    ]
