# Generated by Django 4.2.5 on 2023-12-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0020_alter_dietmeal_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='fish_free',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='gluten_free',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='lactose_free',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='nut_free',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='soy_free',
        ),
        migrations.AddField(
            model_name='meal',
            name='fish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='lactose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='nut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='soy',
            field=models.BooleanField(default=False),
        ),
    ]
