# Generated by Django 4.2.5 on 2024-01-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inz_server', '0022_userdiet_activity_level_userdiet_age_userdiet_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiet',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
